name: CI/CD Pipeline

on: [push]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image with Buildx
      - name: Build Docker image with Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: mirzaakhena/calculator:latest

      # Run tests using the built Docker image
      - name: Run Tests in Docker
        run: docker run mirzaakhena/calculator:latest npm test

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mirzaakhena/calculator:latest
          platforms: linux/amd64,linux/arm64

      # # Configure AWS credentials
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1 # Change to your AWS region

      # # Update kubeconfig for EKS
      # - name: Set up kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --region us-east-1 --name mirza-eks-fargate

      # # Deploy to EKS
      # - name: Deploy to Amazon EKS
      #   run: |
      #     kubectl apply -f ./k8s/deployment.yml
      #     kubectl apply -f ./k8s/service.yml
